### ISSUE TITLE
`LocalDiskMessenger.StartMessageProcessorAsync` throws `NotImplementedException`

### ISSUE THREAD

**Issue by candoumbe** [robinrodricks/FluentStorage#14]
Package version : `5.0.0`

Looking at the [code](https://github.com/robinrodricks/FluentStorage/blob/39a4d637486e13b54fe22337d15602cdda9c348e/FluentStorage/Messaging/Files/LocalDiskMessenger.cs#L141), seems like this method is indeed not implemented (yet ?).

Are there any plan on implementing this method ?
Is there any workaround in the meantime ?

**Comment by robinrodricks** [comment]
No plan to implement, you are free to submit a PR. Thanks.

**Comment by candoumbe** [comment]
I'm working on it
https://github.com/robinrodricks/FluentStorage/compare/develop...candoumbe:feature/messaging/local-disk-start-processor?expand=1
