### ISSUE TITLE
Update Newtonsoft.Json to 13.0.1+

### ISSUE THREAD

**Issue by candoumbe** [robinrodricks/FluentStorage#18]
The Newtonsoft.Json v12.0.3 package used in the library has a [known vulnerability](https://github.com/advisories/GHSA-5crp-9r3c-p9vr)
that was fixed in 13.0.1+

This could help in the adoption of this library (which is really handy by the way)

**Comment by robinrodricks** [comment]
Will look into it, thanks.

**Comment by robinrodricks** [comment]
I cannot find any reference to newtonsoft.

**Comment by candoumbe** [comment]
> I cannot find any reference to newtonsoft.

@robinrodricks 
Here's the reference : https://github.com/advisories/GHSA-5crp-9r3c-p9vr

**Comment by robinrodricks** [comment]
We are not referencing newtonsoft, we are referencing netbox, so I am trying to remove netbox.

**Comment by candoumbe** [comment]
> We are not referencing newtonsoft, we are referencing netbox, so I am trying to remove netbox.

My bad ... I tought I saw `Newtonsoft.Json` version `12.x` somewhere in this repository 😅

**Comment by robinrodricks** [comment]
I'll do you one better. All released!
