### ISSUE TITLE
What about minio?

### ISSUE THREAD

**Issue by Cricle** [robinrodricks/FluentStorage#21]
Will it support minio later?

**Comment by robinrodricks** [comment]
You can contribute support if you want.

**Comment by dammitjanet** [comment]
Possibly a little bit late to the conversation here, but the AWS Blob implementation does take an optional serviceUrl parameter (the region parameter should not be provided or should be explicitly null when this is used), and this allows the AWSS3BlobStorage to communicate with S3 Compatible storage such as Minio.

The functionality for this is provided by the Amazon AWS SDK, specifically the AmazonS3Config (base calls ClientConfig)

**Comment by robinrodricks** [comment]
Implemented in this PR - https://github.com/robinrodricks/FluentStorage/pull/63

**Comment by robinrodricks** [comment]
Released.

https://www.nuget.org/packages/FluentStorage.AWS/5.3.0

**Comment by robinrodricks** [comment]
Documented.

https://github.com/robinrodricks/FluentStorage/wiki/AWS-S3-Storage
