### ISSUE TITLE
AwsS3BlobStorage wants to create a new bucket on read.

### ISSUE THREAD

**Issue by AntMaster7** [robinrodricks/FluentStorage#27]
I want to read an object from an S3 storage with ReadBytesAsync. However, I get an exception saying that I am not authorized to perform create-bucket. Why do I need that permission for reading?

![image](https://github.com/robinrodricks/FluentStorage/assets/4333991/c8060a7e-332a-4c28-aaae-caffdb94f555)

Edit: I found the issue in the implementation. The method GetClientAsync in AwsS3BlobStorage makes a PutBucket request:

https://github.com/robinrodricks/FluentStorage/blob/1dd683ac51ee896c77b055ee6e23a05d23a46e6d/FluentStorage.AWS/Blobs/AwsS3BlobStorage.cs#L113

Why does it do that? It should at least check if the bucket already exists.

You can fix it like so:

```C#
private async Task<AmazonS3Client> GetClientAsync() {
	if (!_initialised) {
		var bucketExists = await AmazonS3Util.DoesS3BucketExistV2Async(_client, _bucketName);
		if (!bucketExists)  {
			var request = new PutBucketRequest { BucketName = _bucketName };

			await _client.PutBucketAsync(request).ConfigureAwait(false);
		}

		_initialised = true;
	}

	return _client;
}
```
		
I can do a PR if you want?

**Comment by robinrodricks** [comment]
Yes please make a PR with a fix, it would be highly appreciated!

**Comment by robinrodricks** [comment]
Thanks a lot!
