### ISSUE TITLE
Rijndael is obsolete in .Net 6 and above

### ISSUE THREAD

**Issue by dammitjanet** [robinrodricks/FluentStorage#33]
As rijndael has become [obsolete in .net6 and above](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.rijndael?view=net-6.0), are there any plans to change the default from Rijndael to Aes in [SymmetricEncryptionSink.cs](https://github.com/robinrodricks/FluentStorage/blob/develop/FluentStorage/Blobs/Sinks/Impl/SymmetricEncryptionSink.cs)

I know I can write my own transform, to implement, however I think this should be at least considered

**Comment by robinrodricks** [comment]
If you have time can you please file a PR for this change I would greatly appreciate it!

**Comment by robinrodricks** [comment]
Completed and released.
