### ISSUE TITLE
ZipArchive contains empty named folder at root

### ISSUE THREAD

**Issue by ckpearson** [robinrodricks/FluentStorage#39]
When using the zip-backed module, Windows explorer claims the archive is empty despite being > 0 size.

Opening the archive in 7-Zip shows a folder at the top level, displayed as '_', and when browsing to it the data I'm expecting at root is there, and the path in the UI shows as:

`my_zip.zip\\`

I think what might be happening is that a leading '/' is being provided when getting an entry in the archive, but I'm not 100% on this.

**Comment by robinrodricks** [comment]
Can you write a small c# console test program and post it here so I can check it out?

**Comment by robinrodricks** [comment]
Any fix and PR will be greatly appreciated.

**Comment by robinrodricks** [comment]
Thanks for the fix.
