### ISSUE TITLE
Aws s3 incorrect handle content-type: application/xml; charset=utf-8

### ISSUE THREAD

**Issue by Pchol** [robinrodricks/FluentStorage#49]
Some aws s3 compatible services return content-type header with charset field and AWSSDK.S3 version less then 3.7.202 incorrect handle response if error occur.
See here https://github.com/aws/aws-sdk-net/issues/3009

Create [mr](https://github.com/robinrodricks/FluentStorage/pull/48) to fix this.

**Comment by robinrodricks** [comment]
OK will update and release

**Comment by robinrodricks** [comment]
Done

https://www.nuget.org/packages/FluentStorage.AWS/5.2.3
