### ISSUE TITLE
support .NET 8

### ISSUE THREAD

**Issue by ductai202** [robinrodricks/FluentStorage#51]
Hi Guys, do you have plan to upgrade the library to support .NET 8. Thank you

**Comment by robinrodricks** [comment]
Why cant you use it as is? What is missing for .NET 8?

**Comment by ductai202** [comment]
No i'm just asking. Because our product plan to update .NET8, and not sure the library can compatible with it. I ask to confirm 😁

**Comment by robinrodricks** [comment]
It should work.
