### ISSUE TITLE
[Bug] FluentStorage.SFTP WriteAsync with append=true does not do anything

### ISSUE THREAD

**Issue by beeradmoore** [robinrodricks/FluentStorage#58]
The `append` argument does not appear to do anything in `WriteAsync` for `FluentStorage.SFTP`.

```
await remoteStorage.WriteAsync("/home/test/test_document_2", new byte[] { (byte)'1' }, true);
```
If I run this multiple times I'd expect `1` to be appended to the file, but it is not.

PR #57 was updated to solve this.

**Comment by robinrodricks** [comment]
Fixed by OP.
