### ISSUE TITLE
The MinIO extension method in FluentStorage.Factory is missing the "IBlobStorageFactory this" parameter

### ISSUE THREAD

**Issue by AloisMaierhofer** [robinrodricks/FluentStorage#65]
The MinIO (meant to be) extension method in `FluentStorage.Factory` is missing the `IBlobStorageFactory this` parameter.

As a workaround one can call `FluentStorage.Factory.MinIO` directly.

If more assemblies that implement the `FluentStorage.Factory` extension methods class (for example AWS and Azure), additional steps are required to be able to select the AWS - related version of this class:
1. add an alias to the referenced _FluentStorage.AWS_ assembly, let's say "FluentStorageAWS" (see [MS documentation](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0433))
2. add the statement `extern alias FluentStorageAWS;` at the very beginning of the file you need it (before usings)
3. call it via prepending the alias to the namespace: `FluentStorageAWS.FluentStorage.Factory.MinIO(...)`

**Comment by robinrodricks** [comment]
Is there a fix I can do at the library level instead of all these workarounds?

**Comment by AloisMaierhofer** [comment]
I guess it should be very easy:

in class `FluentStorage.Factory` in the _FluentStorage.AWS_ project

just add the `IBlobStorageFactory this` parameter:
```
public static IBlobStorage MinIO(
  this IBlobStorageFactory factory,             // missing parameter in v5.3.0
  string accessKeyId,
  string secretAccessKey,
  string bucketName,
  string awsRegion,
  string minioServerUrl,
  string sessionToken = null)
{
  return (IBlobStorage) AwsS3BlobStorage.FromMinIO(accessKeyId, secretAccessKey, bucketName, awsRegion, minioServerUrl, sessionToken);
}
```
this should do the trick, actually.

**Comment by robinrodricks** [comment]
Done.

https://www.nuget.org/packages/FluentStorage.AWS/5.3.1

**Comment by AloisMaierhofer** [comment]
Your prompt response is highly appreciated.
