### ISSUE TITLE
FluentStorage.Azure.Blobs.WriteAsync does not support "append=true"

### ISSUE THREAD

**Issue by gentledepp** [robinrodricks/FluentStorage#79]
Even though the method signature suggests it, 
`AzureBlobStorage`s 
```csharp 
public async Task WriteAsync(
      string fullPath,
      Stream dataStream,
      bool append = false,
      CancellationToken cancellationToken = default (CancellationToken))
```

setting `append` to `true` still just overwrites any preexisting blob.

This is because it uses `BlockBlobClient.UploadAsync` internally, where the [documentation]((https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blockblobclient.uploadasync?view=azure-dotnet)) clearly states:

> The [UploadAsync(Stream, BlobUploadOptions, CancellationToken)](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blockblobclient.uploadasync?view=azure-dotnet#azure-storage-blobs-specialized-blockblobclient-uploadasync(system-io-stream-azure-storage-blobs-models-blobuploadoptions-system-threading-cancellationtoken)) operation overwrites the contents of the blob, creating a new block blob if none exists. Overwriting an existing block blob replaces any existing metadata on the blob.

**Comment by gentledepp** [comment]
Note.
Naively using the `OpenWriteAsync` API that - by its signature - _supports_ appending to an existing blockblob like so:

```csharp
	public async Task WriteAsync(string fullPath, Stream dataStream,
		   bool append = false, CancellationToken cancellationToken = default) {
			GenericValidation.CheckBlobFullPath(fullPath);

			if (dataStream == null)
				throw new ArgumentNullException(nameof(dataStream));

			(BlobContainerClient container, string path) = await GetPartsAsync(fullPath, true).ConfigureAwait(false);

			BlockBlobClient client = container.GetBlockBlobClient(path);

			try {
				var targetStream = await client
					.OpenWriteAsync(!append, new BlockBlobOpenWriteOptions(), cancellationToken: cancellationToken)
					.ConfigureAwait(false);
				await dataStream.CopyToAsync(targetStream, 4096, cancellationToken).ConfigureAwait(false);
				// await client.UploadAsync(
				//    new StorageSourceStream(dataStream),
				//    cancellationToken: cancellationToken).ConfigureAwait(false);
			}
			catch (RequestFailedException ex) when (ex.ErrorCode == "OperationNotAllowedInCurrentState") {
				//happens when trying to write to a non-file object i.e. folder
			}
		}


```
throws an Exception
> System.ArgumentException : BlockBlobClient.OpenWrite only supports overwriting
   bei Azure.Storage.Blobs.Specialized.BlockBlobClient.<OpenWriteInternal>d__58.MoveNext()

So this is a dead end too...

**Comment by gentledepp** [comment]
Since we have potentially _huge_ files we need to stream to Azure Blobstorage, the only viable alternative I found was to extend the `IAzureBlobStorage` interface with a new method 
`Task<Stream> OpenWriteAsync(string fullPath, CancellationToken cancellationToken = default);`

**Comment by robinrodricks** [comment]
Closing as PR is accepted.
