### ISSUE TITLE
Vulnerable package dependencies

### ISSUE THREAD

**Issue by dammitjanet** [robinrodricks/FluentStorage#82]
Package dependencies with vulnerabilities highlighted by Visual Studio's NuGet vulnerability inspection:

https://github.com/advisories/GHSA-m5vv-6r4h-3vj9
 - Azure Identity
   -  `< 1.11.4`
 - Microsoft.Identity.Client
   -  `>= 4.49.1, < 4.60.4`
   -  `>= 4.61.0, < 4.61.3`

https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
 - System.Text.Json
   -  `>= 7.0.0, < =8.0.3`

**Comment by dammitjanet** [comment]
I'll have a PR for this probably tomorrow

**Comment by robinrodricks** [comment]
Thanks for your PR.
