### ISSUE TITLE
Migrate to Microsoft.IO.RecyclableMemoryStream > 3.0.0

### ISSUE THREAD

**Issue by dammitjanet** [robinrodricks/FluentStorage#84]
I've come across an issue whereby using a different package that targets [Microsoft.IO.RecyclableMemoryStream](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream) version 3.0.0 or above causes an issue with the use of Microsoft.IO.RecyclableMemoryStream v 2.3.2 which is used in FluentStorage

The issue manifests as an error as follows:

```
System.MissingMethodException: Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream()'.
   at FluentStorage.Blobs.Sinks.SinkedStream.TransformToMemoryStream(String fullPath, Stream parentReadStream, ITransformSink[] sinks)
   at FluentStorage.Blobs.Sinks.SinkedStream..ctor(Stream parentReadStream, String fullBlobPath, ITransformSink[] transformSinks)
   at FluentStorage.Blobs.Sinks.SinkedBlobStorage.WriteAsync(String fullPath, Stream dataSourceStream, Boolean append, CancellationToken cancellationToken)
   at FluentStorage.Blobs.BlobStorageExtensions.WriteAsync(IBlobStorage provider, String fullPath, Byte[] data, Boolean append, CancellationToken cancellationToken)

```
and relates to this change between version 2 and v3

> All overloads of RecyclableMemoryStreamManager.GetStream now return type RecyclableMemoryStream instead of MemoryStream.

Obviously, this is a major change and may result in a major version change for FluentStorage as the impact throughout the library will be considerable.

**Comment by dammitjanet** [comment]
Ok - there is a PR for this

I made the simplest change I could see on the only file that uses the RecyclableMemoryStream, built, packed and tested the resulting Nuget package in non-working code and it now works as expected.

Since SinkedStream is not a public class and cannot be accessed, and acts like a MemoryStream (it's parent class), I beleive it can be rolled out as is.

The issue is as noted, that any update to Microsoft.IO.RecyclableMemoryStream where the users project already contains the existing older version and that relies on GetStream() being a MemeryStream and not a RecyclableMemoryStream will just cause other package maintainers using FluentStorage the same headache.

**Comment by robinrodricks** [comment]
Thanks for your PR!
